### ISSUE TITLE
The system cannot create /results/ folders for some bugs in Bears

### ISSUE THREAD

**Issue by Kaka727** [program-repair/RepairThemAll#7]
Hi, I executed "./repair.py jKali --benchmark Bears" and it finished. As expected, in the result/Bears folder, it should contain 71 folders. However, it only contains 43 folders. 
That is to say, the system fails to create results folders for some bugs. I have checked it. These bugs are from projects like linkedin-point, molgenis-molgenis, openzipkin-zipkin....and so on.
I find when it's woking, it can download the buggy project into /tmp/. It just does not record the results.

Anyone can explain this strange thing?

**Comment by Kaka727** [comment]
The command line information is 
Command 'cd /tmp/jKali_Bears_molgenis-molgenis_336061452-336065127;
mvn com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info -q;
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/kaka/Desktop/RepairThemAll/script/core/runner/local/LocalRunner.py", line 41, in run
    task.run()
  File "/home/kaka/Desktop/RepairThemAll/script/core/runner/RepairTask.py", line 30, in run
    return self.tool.repair(self)
  File "/home/kaka/Desktop/RepairThemAll/script/core/repair_tools/Astor.py", line 45, in repair
    if bug.compliance_level() > 7:
  File "/home/kaka/Desktop/RepairThemAll/script/core/Bug.py", line 62, in compliance_level
    return self.benchmark.compliance_level(self)
  File "/home/kaka/Desktop/RepairThemAll/script/core/benchmarks/Bears.py", line 230, in compliance_level
    info = self._get_project_info(bug)
  File "/home/kaka/Desktop/RepairThemAll/script/core/benchmarks/Bears.py", line 81, in _get_project_info
    info = json.loads(subprocess.check_output(cmd, shell=True))
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'cd /tmp/jKali_Bears_molgenis-molgenis_336061452-336065127;
mvn com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info -q;
' returned non-zero exit status 1
1 Finished, 0 Patched, 1 Error

But I am sure I installed the maven plugin provided by your link.

**Comment by tdurieux** [comment]
I looked at the log of our experiment, and we failed to configure correctly the repair tools for `molgenis-molgenis_336061452-336065127`. 
We did not find the bin directories for the failing module. I need to investigate why. 

However, it is not normal that the execution did not create a repository. That should never happen

**Comment by Kaka727** [comment]
I will try again. But what the error information indicates for? Other projects work well while this project fails.




------------------ Original ------------------

**Comment by tdurieux** [comment]
I dont know for your issue, we did not face it.
Could you run ```
python checkout.py -b Bears -i molgenis-molgenis_336061452-336065127 -w <path>;
cd <path>;
mvn -X com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT:info;
```
And send me the error message?

Thanks

**Comment by Kaka727** [comment]
It failed again.

Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.molgenis:molgenis-security:jar:6.0.0-SNAPSHOT, nl.captcha:simplecaptcha:jar:1.2.1: Could not find artifact org.molgenis:molgenis-security:jar:6.0.0-SNAPSHOT
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:422)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:224)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:338)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:202)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:223)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:263)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:200)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :molgenis-core-ui

**Comment by tdurieux** [comment]
strange it seems that the dependency does not exist anymore.
can you do a 
`mvn package -Dmaven.test.skip` and see if it is compiling?

**Comment by tdurieux** [comment]
Can you check if you have `javax` installed?

**Comment by tdurieux** [comment]
You will also need `rhino` js vm for java.

You can install with
```
cd openjdk-1.7.0/jre/lib/ext
wget http://central.maven.org/maven2/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar
wget http://central.maven.org/maven2/org/apache/bsf/bsf-all/3.0-beta3/bsf-all-3.0-beta3.jar
```

**Comment by Kaka727** [comment]
I haven't installed javax.
How to install it please?

**Comment by tdurieux** [comment]
Normally, it is included with the Java jdk, and when it is not I always struggled to solve the problem. 
I dont remember how to install it.
Sorry

**Comment by Kaka727** [comment]
I find this error influences many bugs such as linkedin-pinot-342188288-342446553

I have downloaded a javax.jar. So where should I put it? I am not familiar with it.

**Comment by tdurieux** [comment]
I think it should be included in the classpath of the execution. 
Maybe you can add it here: https://github.com/program-repair/RepairThemAll/blob/master/script/core/Bug.py#L59

```
return "<path_to_jar_>:" + self.benchmark.classpath(self)
```

**Comment by Kaka727** [comment]
I tried this way but it failed again.
